name: "Special on HVC1"

on:
  workflow_dispatch:
    inputs:
      GeoCode:
        description: "GeoCode"
        required: true
        type: choice
        options:
        - NewYork
        - Shanghai
      JobSequence:
        description: "JobSequence"
        required: true
        type: number
        default: 0
      EncPreset:
        description: "EncPreset"
        required: true
        default: "veryslow"
        type: choice
        options:
        - placebo
        - veryslow
        - slower
      Resolution:
        description: "Resolution"
        required: true
        type: choice
        options:
        - "720"
        - "576"
      Purpose:
        description: "Purpose"
        required: true
        type: choice
        options:
        - arc

env:
  SOURCERY: ${{ secrets.SOURCERY }}
  LocationOnIndex: "td:/MiraculouSourceryZ"
  R3NC0D3R: "HVC1"
  Variant: "Special"
  GeoCode: ${{ github.event.inputs.GeoCode }}
  SubLocation: "Sp0${{ github.event.inputs.GeoCode }}"
  InFilePrefix: "Miraculous.World.${{ github.event.inputs.GeoCode }}"
  JobSequence: ${{ github.event.inputs.JobSequence }}
  EncPreset: ${{ github.event.inputs.EncPreset }}
  Resolution: ${{ github.event.inputs.Resolution }}
  Purpose: ${{ github.event.inputs.Purpose }}
  RCLONE_CONFIG_URL: ${{ secrets.RCLONE_CONFIG_URL }}
  FTOOL_CONVERTER: ${{ secrets.FTOOL_CONVERTER }}
  FTOOL_PROBER: ${{ secrets.FTOOL_PROBER }}

jobs:

  primary:
    runs-on: ubuntu-latest

    outputs:
      FrameRate: ${{ steps.set-params.outputs.FrameRate }}
      ExactFrameRate: ${{ steps.set-params.outputs.ExactFrameRate }}
      GOPSize: ${{ steps.set-params.outputs.GOPSize }}
      GOPType: ${{ steps.set-params.outputs.GOPType }}
      APIState: ${{ steps.set-params.outputs.APIState }}
      finalChunk: ${{ steps.set-params.outputs.finalChunk }}
      matrix: ${{ steps.set-params.outputs.matrix }}
      safile_json: ${{ steps.set-params.outputs.safile_json }}
    steps:
      - uses: actions/checkout@v3
      - name: Set GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Checkout EncToolZ
        env:
          ReqdEncToolZ: "rtools"
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY
          source ./SOURCERY &>/dev/null && rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./21-EncTool-b473ab7b69f5
      - name: Create EncMatrix
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY
          source ./SOURCERY &>/dev/null && rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./41-EncMtrx-9006e1ebae5b
      - name: Pass Parameters to EncMatrix
        id: set-params
        run: |
          echo "[i] Passing Parameters to EncMatrix..."
          echo "::set-output name=FrameRate::${FrameRate}"
          echo "::set-output name=ExactFrameRate::${ExactFrameRate}"
          echo "::set-output name=GOPSize::${GOPSize}"
          echo "::set-output name=GOPType::${GOPType}"
          echo "::set-output name=APIState::${APIState}"
          echo "::set-output name=finalChunk::${finalChunk}"
          echo "::set-output name=matrix::${matrix}"
          echo "::set-output name=safile_json::${safile_json}"

  enc_hvc1:
    runs-on: ubuntu-latest
    needs: primary

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        ChunkNum: ${{fromJson(needs.primary.outputs.matrix)}}

    env:
      ChunkNum: ${{ matrix.ChunkNum }}
      FrameRate: ${{ needs.primary.outputs.FrameRate }}
      ExactFrameRate: ${{ needs.primary.outputs.ExactFrameRate }}
      GOPType: ${{ needs.primary.outputs.GOPType }}
      GOPSize: ${{ needs.primary.outputs.GOPSize }}

    steps:
      - uses: actions/checkout@v3
      - name: Set GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Checkout EncToolZ
        env:
          ReqdEncToolZ: "ftools rtools"
          safile_json: ${{ needs.primary.outputs.safile_json }}
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY
          source ./SOURCERY &>/dev/null && rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./21-EncTool-b473ab7b69f5
      - name: HVC1 R3NC0D3R - Chunk_${{env.ChunkNum}} of ${{env.SubLocation}} - AIO
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY
          source ./SOURCERY &>/dev/null && rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./68-EncPreWr-a3327ad30631
          DEOBFUS ./72-EncX-ae3aca956963

  postEnc:
    runs-on: ubuntu-latest
    needs: [primary, enc_hvc1]

    env:
      APIState: ${{ needs.primary.outputs.APIState }}

    steps:
      - uses: actions/checkout@v3
      - name: Trigger Another Workflow
        if: env.APIState == 'trigger'
        env:
          GH_TOKEN2: ${{ secrets.GH_TOKEN2 }}
          GH_TOKEN3: ${{ secrets.GH_TOKEN3 }}
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY
          source ./SOURCERY &>/dev/null && rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./99-EncZ-948448f0c76f
      - name: Set GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        if: env.APIState == 'merge'
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Checkout EncToolZ
        if: env.APIState == 'merge'
        env:
          ReqdEncToolZ: "mtools rtools"
          safile_json: ${{ needs.primary.outputs.safile_json }}
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY
          source ./SOURCERY &>/dev/null && rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./21-EncTool-b473ab7b69f5
      - name: Merge Whole Episode - ${{env.SubLocation}}
        if: env.APIState == 'merge'
        env:
          GOPType: ${{ needs.primary.outputs.GOPType }}
          finalChunk: ${{ needs.primary.outputs.finalChunk }}
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY
          source ./SOURCERY &>/dev/null && rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./91-EncMr-db991ece1d25
