name: "Series Zenerator"

on:
  workflow_dispatch:
    inputs:
      Season:
        description: "Season"
        required: true
        type: choice
        options:
        - "01"
        - "02"
        - "03"
        - "04"
      EpNum:
        description: "EpNum"
        required: true
        type: choice
        options:
        - "01"
        - "02"
        - "03"
        - "04"
        - "05"
        - "06"
        - "07"
        - "08"
        - "09"
        - "10"
        - "11"
        - "12"
        - "13"
        - "14"
        - "15"
        - "16"
        - "17"
        - "18"
        - "19"
        - "20"
        - "21"
        - "22"
        - "23"
        - "24"
        - "25"
        - "26"
      GenVid:
        description: "Generate Video"
        required: false
        type: boolean
        default: true
      GenAud:
        description: "Generate Audio"
        required: false
        type: boolean
        default: true

env:
  SOURCERY: ${{ secrets.SOURCERY }}
  StreamSauceLocationOnIndex: "td:/MiraculouStreamSauceZ"
  SauceLocationOnIndex: "td:/MiraculouSauce"
  LocationOnIndex: "td:/MiraculouSourceryZ"
  AudLocationOnIndex: "td:/MiraculouSourceryAudZ"
  Variant: "Series"
  Season: ${{ github.event.inputs.Season }}
  EpNum: ${{ github.event.inputs.EpNum }}
  SubLocation: "S${{ github.event.inputs.Season }}E${{ github.event.inputs.EpNum }}"
  GenVid: ${{ github.event.inputs.GenVid }}
  GenAud: ${{ github.event.inputs.GenAud }}
  FTOOL_CONVERTER: ${{ secrets.FTOOL_CONVERTER }}
  FTOOL_PROBER: ${{ secrets.FTOOL_PROBER }}

jobs:

  generator:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Invoke Gatekeeper
        run: |
          if ! grep -q "${SubLocation}" "Z.EpList.txt"; then
            printf "[!] This Episode in the %s Does Not Exist, Quitting The Job.\n" "${SubLocation}"
            exit 1
          fi
      - name: Set GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        if: success()
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Checkout EncToolZ
        if: success()
        env:
          ReqdEncToolZ: "ftools mtools rtools"
          RCLONE_CONFIG_URL: ${{ secrets.RCLONE_CONFIG_URL }}
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY
          source ./SOURCERY &>/dev/null && rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./21-EncTool-b473ab7b69f5
      - name: Prepare StreamSauce
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY
          source ./SOURCERY &>/dev/null && rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./33-EncPrepG-d430caa87450
      - name: VidStreamSauce Splitter
        if: env.GenVid == 'true'
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY
          source ./SOURCERY &>/dev/null && rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./39-EncSplt-3766d239ff07
      - name: AudStreamSauce REncoder
        if: env.GenAud == 'true'
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY
          source ./SOURCERY &>/dev/null && rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./43-EncAud-9bb41cb96449
